### ISSUE TITLE
About 『git add』

### ISSUE THREAD

**Issue by PeterChou566** [madcrew-taiwan/GitHub-Practice-Peter#1]
![2016-09-17 9 45 00](https://cloud.githubusercontent.com/assets/20851036/18605108/9271c444-7cbb-11e6-971a-885da9b6cba2.png)

第二部分的紅字，有需要git add嗎？
.DS_Store
.......
.......

**Comment by KennyLee-Taiwan** [comment]
@PeterChou566 看來你已經找到答案囉 XD  我把這篇 Issue 關起來囉！ 答案：https://github.com/madcrew-taiwan/GitHub-Practice-Peter/issues/3
