### ISSUE TITLE
Solution - About 『git add』

### ISSUE THREAD

**Issue by PeterChou566** [madcrew-taiwan/GitHub-Practice-Peter#3]
**# .DS_Store** basically just handles settings on the directory it's in, and as such it's useless to share this with other developers. And we should try to ignore it!!

[In terminal] add these 2 command , and that's done!!  .DS_Store won't appear again~~
`shuutaigoutekiMacBook-Air:~ PeterChou$ git config --global core.excludesfile ~/.gitignore
`
`shuutaigoutekiMacBook-Air:~ PeterChou$ echo .DS_Store >> ~/.gitignore`

ref: http://jesperrasmussen.com/2013/11/13/globally-ignore-ds-store-on-mac/

**Comment by KennyLee-Taiwan** [comment]
@PeterChou566 讚！長知識了！建議可以把 [In terminal] 那段寫進我們的 GitHub 共同開發 SOP 雲端文件裡面唷，非常有幫助！（https://drive.google.com/drive/folders/0BxQFV75xh6omZER6QWl5azVNNDA?usp=sharing）

我把你原來的問題連結過來，然後把這篇 Issue 結案囉！

原始問題： https://github.com/madcrew-taiwan/GitHub-Practice-Peter/issues/1
